### ISSUE TITLE
Can I only enable the package for admins?

### ISSUE THREAD

**Issue by Barmunksu** [viacreative/sudo-su#10]
how register Provider for only one user without APP_DEBUG?

```
class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        if (env('APP_DEBUG')) {
            $this->app->register('VIACreative\SudoSu\ServiceProvider');
        }
    }
}
```

```
@if (Auth::check() && Auth::user()->id == 1)
    @include('sudosu::user-selector')
@endif
```

**Comment by mrterryh** [comment]
You could only include the view for admins (as shown in your example), but the routes wouldn't be protected:

https://github.com/viacreative/sudo-su/blob/master/src/RouteServiceProvider.php

Perhaps admin-restricted controls is something we should consider implementing?

**Comment by Barmunksu** [comment]
if i could override this routes in my default routes.php, it's will be great.
After that I will be able to restrict access by ip and user middleware

**Comment by mrterryh** [comment]
I'll have a think about this over the weekend. It may be worth implementing some kind of middleware in the package itself.

**Comment by krve** [comment]
I'm pretty sure you actually can override the routes by copying what the package has and wrapping them in some middleware in your own routes.php/web.php
```php
Route::group(['middleware' => 'YOUR-MIDDLEWARE'], function () {
    Route::post('/sudosu/login-as-user', '\VIACreative\SudoSu\Controller\SudoSuControllerSudoSuController@loginAsUser')
        ->name('sudosu.login_as_user');
    Route::post('/sudosu/logout', '\VIACreative\SudoSu\Controller\SudoSuControllerSudoSuController@logout')
        ->name('sudosu.logout');
});
```

Depending on your laravel version you should also add the `web` middleware.

**EDIT**: You would probably have to specify the full namespace of the controller. `\VIACreative\SudoSu\Controller\SudoSuController`
