### ISSUE TITLE
Content being injected outside of <html> tag

### ISSUE THREAD

**Issue by krve** [viacreative/sudo-su#4]
The content is being injected outside of the html tag.

I think it might be better to simply let the user include a partial in their layout file, instead of automatically injecting the HTML into the response. This would also fix the issue of the partial being injected into api requests. So for example:

```php
@include('sudosu::selector')
```

This way you can decide what pages you want it to display on, and all it requires is a little extra setup.
 (Adding one line to your layout file)

**Comment by mrterryh** [comment]
Yeah, this is a good idea I think. Do you want to update your PR and I'll merge it in right away? If not, I'll get this implemente early next week :)

**Comment by krve** [comment]
Yeah, I'll take a look at it this weekend and update my PR.

**Comment by mrterryh** [comment]
Awesome, thanks so much @krve!

**Comment by mrterryh** [comment]
Closing this as the PR is now merged :)
