### ISSUE TITLE
Undefined variable: hasSudoed

### ISSUE THREAD

**Issue by dragonfire1119** [viacreative/sudo-su#7]
Problem
========

I just installed this in my Laravel project & I get ``Undefined variable: hasSudoed`` the button seems to be down on the right & is working.

Versions
========

Laravel 5.4
viacreative/sudo-su 1.0

**Comment by Te7a-Houdini** [comment]
make php artisan vendor:publish 

then go to config/sudosu.php , you will find this array

 'allowed_tlds' => ['dev', 'local']

append your domain to it , 

like if my url is myapp.dev/user/login i will make this 

 'allowed_tlds' => ['dev', 'local','myapp.dev']

**Comment by dragonfire1119** [comment]
@Te7a-Houdini Thanks for the reply! I have tried your solution & unfortunately it still presents me with  ``Undefined variable: hasSudoed``.

**Comment by dragonfire1119** [comment]
If I remove

```
@if (env('APP_DEBUG'))
    @include('sudosu::user-selector')
@endif
```

the partial from my layout it works & is still there. That's weird the readme says include that in the layout?

**Comment by Te7a-Houdini** [comment]
@dragonfire1119  try to use the new release  ,and check if that happens again

"viacreative/sudo-su": "^1.1"

**Comment by mrterryh** [comment]
Seems to be working for me? It could have something to do with the fact that I just pushed a new release (1.1). Maybe try that version?

**Comment by dragonfire1119** [comment]
@Te7a-Houdini Thanks for the help! @mrterryh Must of been a bug with the 1.0.
